=== julenn06/dam/DAM1/Lenguaje de Marcas/3.Eval/XML/XSD/ariketa06/6.6/ariketa06-6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="max50">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="max9">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nanBalidatu">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="portzentaia">
        <xs:restriction base="xs:string">
                <xs:pattern value="\d{2}%"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ikasleak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ikaslea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izena" type="xs:string"/>
                            <xs:element name="helbidea">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="kalea">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="zbk">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                    <xs:maxInclusive value="1000"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="herria" type="max50"/>
                                        <xs:element name="probintzia" type="max50"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="telefonoa" type="max9"/>
                                <xs:element name="mugikorra" minOccurs="3" maxOccurs="3" type="max9"/>
                            </xs:choice>
                            <xs:element name="emaila" type="xs:string"/>
                            <xs:element name="elbarritasuna" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="gradua" type="portzentaia"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nan" type="nanBalidatu"/>
                        <xs:attribute name="jaiotza" type="xs:date"/>
                        <xs:attribute name="errepikatzailea" type="xs:boolean" use="optional" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== julenn06/dam/DAM1/Lenguaje de Marcas/3.Eval/XML/XSD/ariketa06/6.6/fitxategia-6.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ariketa06-6.xsd">
	<ikaslea nan="12345678A" jaiotza="1990-12-12" errepikatzailea="false">
		<izena>Iraide Etxeberria</izena>
		<helbidea>
			<kalea>Kale nagusia</kalea>
			<zbk>5</zbk>
			<herria>Bilbao</herria>
			<probintzia>Bizkaia</probintzia>
		</helbidea>
		<telefonoa>944000000</telefonoa>
        <emaila>iraide@gmail.com</emaila>
        <elbarritasuna gradua="11%"></elbarritasuna>
	</ikaslea>
	<ikaslea nan="87654321A" jaiotza="1991-01-01" errepikatzailea="true">
		<izena>Joseba Mikel Zarraga</izena>
		<helbidea>
			<kalea>Gorbeia</kalea>
			<zbk>75</zbk>
			<herria>Artea</herria>
			<probintzia>Bizkaia</probintzia>
		</helbidea>
		<mugikorra>944999999</mugikorra>
        <mugikorra>944999999</mugikorra>
        <mugikorra>944999999</mugikorra>
        <emaila>joseba@gmail.com</emaila>
    </ikaslea>	
</ikasleak>
