=== julenn06/dam/DAM1/Lenguaje de Marcas/3.Eval/azterketatxuleta/proba5/proba5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="facultades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="facultad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="decanato" type="xs:string" />
                                        <xs:element name="alumnos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alumno" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre"
                                                                    type="xs:string" />
                                                                <xs:element name="direccion">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="calle"
                                                                                type="xs:string" />
                                                                            <xs:element
                                                                                name="numero"
                                                                                type="xs:string" />
                                                                            <xs:element
                                                                                name="ciudad"
                                                                                type="xs:string" />
                                                                            <xs:element
                                                                                name="provincia"
                                                                                type="xs:string" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="telefono">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="num"
                                                                            type="xs:integer"
                                                                            use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="email"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="nan" use="required" />
                                                            <xs:attribute name="nacimiento"
                                                                type="xs:date" use="required" />
                                                            <xs:attribute name="becario"
                                                                type="xs:boolean" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" use="required" />
            <xs:attribute name="id" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== julenn06/dam/DAM1/Lenguaje de Marcas/3. Eval/azterketatxuleta/proba5/proba5.xml
<?xml version="1.0" encoding="UTF-8"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="proba5.xsd" nombre="Universidad Internacional de la Innovación" id="2002">
    <facultades>
        <facultad id="F01">
            <nombre>Ingeniería</nombre>
            <decanato>Dr. Elena López</decanato>
            <alumnos>
                <alumno nan="12345678A" nacimiento="2001-06-15" becario="true">
                    <nombre>Mario Sánchez</nombre>
                    <direccion>
                        <calle>Carrera 12</calle>
                        <numero>101</numero>
                        <ciudad>Valencia</ciudad>
                        <provincia>Valencia</provincia>
                    </direccion>
                    <telefono num="600123123"/>
                    <email>mario.sanchez@uniinnovacion.edu</email>
                </alumno>
                <alumno nan="87654321B" nacimiento="2002-10-05" becario="false">
                    <nombre>Laura Gómez</nombre>
                    <direccion>
                        <calle>Libertad 8</calle>
                        <numero>58</numero>
                        <ciudad>Barcelona</ciudad>
                        <provincia>Barcelona</provincia>
                    </direccion>
                    <telefono num="600321321"/>
                    <email>laura.gomez@uniinnovacion.edu</email>
                </alumno>
            </alumnos>
        </facultad>
    </facultades>
</universidad>
