=== julenn06/dam/DAM1/Lenguaje de Marcas/3. Eval/azterketatxuleta/proba6/proba6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedidos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pedido">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cliente">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" />
                                                    <xs:element name="direccion">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="calle"
                                                                    type="xs:string" />
                                                                <xs:element name="codigoPostal"
                                                                    type="xs:string" />
                                                                <xs:element name="ciudad"
                                                                    type="xs:string" />
                                                                <xs:element name="provincia"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="telefono">
                                                        <xs:complexType>
                                                            <xs:attribute name="num"
                                                                type="xs:integer" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="productos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="producto"
                                                        maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="descripcion"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="id" use="required" />
                                                            <xs:attribute name="cantidad"
                                                                type="xs:integer" use="required" />
                                                            <xs:attribute name="precioUnitario"
                                                                type="xs:decimal" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="descuento" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required" />
                                    <xs:attribute name="fecha" type="xs:date" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== julenn06/dam/DAM1/Lenguaje de Marcas/3. Eval/azterketatxuleta/proba6/proba6.xml
<?xml version="1.0" encoding="UTF-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="proba6.xsd" id="3003">
    <pedidos>
        <pedido id="P001" fecha="2025-04-26">
            <cliente id="C101">
                <nombre>Andrea Ruiz</nombre>
                <direccion>
                    <calle>Horizonte 22</calle>
                    <codigoPostal>46000</codigoPostal>
                    <ciudad>Valencia</ciudad>
                    <provincia>Valencia</provincia>
                </direccion>
                <telefono num="688112233"/>
            </cliente>
            <productos>
                <producto id="PR01" cantidad="2" precioUnitario="29.99">
                    <descripcion>Ratón inalámbrico Logitech</descripcion>
                </producto>
                <producto id="PR02" cantidad="1" precioUnitario="999.99">
                    <descripcion>Portátil ASUS Zenbook</descripcion>
                </producto>
            </productos>
            <descuento>5</descuento>
        </pedido>
    </pedidos>
</tienda>
