=== julenn06/dam/DAM1/Lenguaje de Marcas/3. Eval/XML/XSD/ariketa06/6.3/ariketa06-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ikasleak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ikaslea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nan" type="xs:string"/>
                            <xs:element name="izena" type="xs:string"/>
                            <xs:element name="helbidea">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="kalea" type="xs:string"/>
                                        <xs:element name="zbk" type="xs:integer"/>
                                        <xs:element name="herria" type="xs:string"/>
                                        <xs:element name="probintzia" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="telefonoa" type="xs:string" minOccurs="0"/>
                                <xs:element name="mugikorra" type="xs:string" minOccurs="3" maxOccurs="3"/>
                            </xs:choice>
                            <xs:element name="emaila" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== julenn06/dam/DAM1/Lenguaje de Marcas/3.Eval/XML/XSD/ariketa06/6.3/fitxategia-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ariketa06-3.xsd">
	<ikaslea>
		<nan>11111111</nan>
		<izena>Iraide Etxeberria</izena>
		<helbidea>
			<kalea>Kale nagusia</kalea>
			<zbk>5</zbk>
			<herria>Bilbao</herria>
			<probintzia>Bizkaia</probintzia>
		</helbidea>
		<telefonoa>944000000</telefonoa>
        <emaila>iraide@gmail.com</emaila>
	</ikaslea>
	<ikaslea>
		<nan>22222222</nan>
		<izena>Joseba Mikel Zarraga</izena>
		<helbidea>
			<kalea>Gorbeia</kalea>
			<zbk>75</zbk>
			<herria>Artea</herria>
			<probintzia>Bizkaia</probintzia>
		</helbidea>
		<mugikorra>944999999</mugikorra>
        <mugikorra>944999999</mugikorra>
        <mugikorra>944999999</mugikorra>
        <emaila>joseba@gmail.com</emaila>
	</ikaslea>	
</ikasleak>
